# Nixpacks config – detecta Python, instala dependências e roda o app
[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmd = "pip install --no-cache-dir -r requirements.txt"

[start]
cmd = "streamlit run main.py --server.port $PORT --server.address 0.0.0.0"
